WITH company_names(name) AS (VALUES
  ('G Bus'),
  ('Basi Zote'),
  ('SABRIN BUS'),
  ('SAFARI EXPRESS'),
  ('PLANET COACH'),
  ('AMBASA LINER BUS SERVICES'),
  ('EARTHPLANE COACH'),
  ('MUHSIN FIRST CLASS'),
  ('ALMA COACH'),
  ('MOYALE RAHA'),
  ('SALAAM CLASSIC COACH'),
  ('MOYALE STAR'),
  ('GATEWAY BUS'),
  ('2NK SACCO'),
  ('Development Team'),
  ('CROWN BUS'),
  ('COAST BUS'),
  ('KETNNO SACCO'),
  ('SHUTTLE'),
  ('NILE COACH BUS SERVICE'),
  ('NYENA SACCO'),
  ('MASH E.A'),
  ('NASIB BUS'),
  ('TRAINING EXPRESS'),
  ('DREAMLINE EXPRESS'),
  ('NAEKANA SACCO'),
  ('GOLDEN COACH'),
  ('GARISSA COACH'),
  ('BUSCAR'),
  ('PALMERS COACH'),
  ('GRAND BUS'),
  ('MOMBASA FRESH'),
  ('Gor Gor'),
  ('DAYAH EXPRESS'),
  ('ENA COACH'),
  ('NABIL'),
  ('CITYLINK COACH'),
  ('SALMAN BUS SERVICES'),
  ('TAHMEED EXPRESS'),
  ('HODAN BUS SERVICE'),
  ('MEDINA BUS SERVICE'),
  ('MABRUK CLASSIC'),
  ('RAYAN COACH'),
  ('WAJIR BUS'),
  ('SIMBA COOL'),
  ('RANDA COACH'),
  ('BAHSAN LUXURY LIMITED'),
  ('i-Fly'),
  ('Expa Limited'),
  ('NILE STAR OLD'),
  ('Kalita Transporters'),
  ('MODERN COAST'),
  ('PRESTIGE SHUTTLE'),
  ('DIAMOND COACH LTD'),
  ('MOMBASA LOGISTICS LIMITED'),
  ('PERISKA'),
  ('DAYAH CITY'),
  ('LIBAN'),
  ('LODWAR PRESTIGE SHUTTLE & PARCEL LIMITED'),
  ('BUKHARI'),
  ('G-Coach Courier'),
  ('Legend Coach Limited'),
  ('ALPHA BUS'),
  ('NORTHERN CITY COACHES'),
  ('WAMO Classic'),
  ('Trippin'' Luxury Shuttle'),
  ('NEYRUS EXPRESS'),
  ('OBAMANA SACCO'),
  ('MUZDALIFA EXPRESS AND PARCEL SERVICES'),
  ('SILVERCRUZ'),
  ('QUICKBUS TRAVELERS'),
  ('TRANSLINE CLASSIC'),
  ('ALAMEEN COACH'),
  ('Dunia Parcel Services LTD'),
  ('FAST CITY COURIER'),
  ('MINA PARCEL SERVICES'),
  ('HIDIG EXPRESS'),
  ('TAYAAN PARCEL COMPANY LIMITED'),
  ('FILLERS EXPRESS'),
  ('SOMKEN'),
  ('SUPER METRO'),
  ('MPASSO'),
  ('SUPER METRO EXECUTIVE'),
  ('Spacelink Logistics'),
  ('Kaliita Transporters'),
  ('Salum Rashid Classic Coach'),
  ('Buscar Courier Services Limited'),
  ('KINATWA SACCO'),
  ('ROYAL TRAVELLERS'),
  ('DAYAH CITY NEW'),
  ('LIBAN COACH'),
  ('SUPER PREMIUM'),
  ('ASAL PARCELS LIMITED'),
  ('TEAM SWAT SHUTTLES'),
  ('TEAM SWAT LOGISTICS & MANAGEMENT LIMITED'),
  ('TestCompany thsdkf kdsjfskdjlkdjfkds'),
  ('ROYAL LINER EXPRESS LIMITED'),
  ('KIDIA ONE EXPRESS'),
  ('UMMAA EXPRESS LIMITED'),
  ('RAHMA BUS SERVICES'),
  ('PACIFIC COACH'),
  ('Golden Courier'),
  ('NOAH CABS'),
  ('Transliner Cruiser'),
  ('Classic Safari Coaches'),
  ('MAU NAROK SHUTTLE'),
  ('Tawakal Express'),
  ('WASAFI NEAT TOURS AND TRAVELS'),
  ('FLYING HORSE TRAVELERS LIMITED'),
  ('DREAM CRUISER'),
  ('NUREIN BUS COMPANY'),
  ('test'),
  ('BUSIA BOARDER PRESTIGE'),
  ('UMEIRA COACH'),
  ('Amana Coach'),
  ('MASH EAST AFRICA LIMITED'),
  ('DATALINER EXPRESS'),
  ('Tasbih Cruiser Services'),
  ('Great Rift Shuttle'),
  ('Loliondo Coach Limited'),
  ('ABANDU SAFARIS'),
  ('EASTERN COACHES'),
  ('DAALO LUXURY BUS SERVICE'),
  ('LIBAN-KAKUMA'),
  ('ABBYSINIA LUXURY'),
  ('NILE STAR'),
  ('VATCAN CITY COASTERS'),
  ('ROYAL AIR BUS'),
  ('SAMARIA'),
  ('GREENLAND'),
  ('GOD IS ONE'),
  ('CHAMVUA EXPRESS OLD'),
  ('SWABRA EXPRESS'),
  ('BROTHER MUSSA'),
  ('CHAMVUA EXPRESS'),
  ('SAIFOO 1'),
  ('SAIFOO 3'),
  ('SAIFOO 2'),
  ('GODS PLAN'),
  ('HABIB CRUISER'),
  ('BOKI TRANS'),
  ('HOMEBOYS SWIFT CONNECTION'),
  ('AL AMEEN LOGISTICS'),
  ('REMBO SHUTTLE'),
  ('SANGAIWE ONE'),
  ('GLODEN TRANS'),
  ('HARFAT COACH LIMITED'),
  ('SALAMA BUS'),
  ('MANDEQ BUS SERVICE LIMITED'),
  ('SIMBA COURIER AND CARGO SERVICES'),
  ('The Simba Cool'),
  ('SUMMIT COACHES'),
  ('TOSHA EXPRESS AND PARCEL SERVICES'),
  ('Tawakal Limited'),
  ('RATCO EXPRESS'),
  ('PULLY LOGISTICS PARCEL SERVICES LIMITED'),
  ('RAYAN CLASSIC'),
  ('BASHCAR BUS SERVICE'),
  ('THE FLEXIS SHUTTLES LIMITED'),
  ('ZAIN COACH LIMITED'),
  ('MARANGU LUXURY COACH'),
  ('Deliva Fasta'),
  ('SILVER COACH'),
  ('CLASSIC COACH')
)
INSERT INTO public.bus_companies(organization_id,name)
SELECT o.id,c.name FROM public.organizations o CROSS JOIN company_names c
ON CONFLICT(organization_id,name) DO NOTHING;
