type Line = { company: string; tickets: number; value: string; cancelled: number; chats_received: number; chats_handled: number; chats_missed: number };
export type ShiftReportPdfData = { workspace: string; employee: string; email: string; shift: string; checkedIn: string; checkedOut: string; unreached: number; vouchers: number; cancelled: number; chatsReceived: number; chatsHandled: number; chatsMissed: number; totalTickets: number; totalValue: string; handover: string; lines: Line[] };

const esc = (s: string) => String(s).replace(/[^\x20-\x7e]/g, "-").replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)");
const money = (s: string) => Number(s).toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export function createShiftReportPdf(data: ShiftReportPdfData) {
  const rows = data.lines.length ? data.lines : [{ company: "No company activity recorded", tickets: 0, value: "0", cancelled: 0, chats_received: 0, chats_handled: 0, chats_missed: 0 }];
  const chunks: Line[][] = []; for (let i = 0; i < rows.length; i += 34) chunks.push(rows.slice(i, i + 34));
  const objects: string[] = [], add = (body: string) => { objects.push(body); return objects.length; };
  const font = add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const bold = add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");
  const pages: number[] = []; const pageBodies: { content: number; page: number }[] = [];
  for (let pageIndex = 0; pageIndex < chunks.length; pageIndex++) {
    let y = 790; const out: string[] = [];
    const text = (x: number, size: number, value: string, b = false) => out.push(`BT /${b ? "B" : "F"} ${size} Tf ${x} ${y} Td (${esc(value)}) Tj ET`);
    const cell = (x: number, size: number, value: string | number, b = false) => out.push(`BT /${b ? "B" : "F"} ${size} Tf ${x} ${y} Td (${esc(String(value))}) Tj ET`);
    out.push("0.12 0.15 0.24 rg 0 750 612 92 re f", "1 1 1 rg"); y = 806; text(40, 20, "ORBIT - SHIFT CHECKOUT REPORT", true); y = 780; text(40, 10, `${data.workspace}  |  Page ${pageIndex + 1} of ${chunks.length}`);
    out.push("0.12 0.15 0.24 rg"); y = 724; text(40, 12, `${data.employee} (${data.email})`, true); y -= 18; text(40, 10, data.shift); y -= 15; text(40, 9, `Check-in: ${data.checkedIn}    Check-out: ${data.checkedOut}`);
    y -= 28; text(30, 11, "BUS COMPANY TICKET AND CHAT ACTIVITY", true); y -= 18;
    cell(30, 7, "Bus company", true); cell(245, 7, "Tickets", true); cell(290, 7, "Value", true); cell(355, 7, "Cancelled", true); cell(415, 7, "Received", true); cell(470, 7, "Handled", true); cell(525, 7, "Missed", true);
    y -= 8; out.push(`0.8 G 28 ${y} m 580 ${y} l S`); y -= 14;
    for (const row of chunks[pageIndex]) {
      cell(30, 7.5, row.company.slice(0, 43)); cell(250, 7.5, row.tickets); cell(290, 7.5, money(row.value)); cell(367, 7.5, row.cancelled); cell(429, 7.5, row.chats_received); cell(484, 7.5, row.chats_handled); cell(539, 7.5, row.chats_missed); y -= 16;
    }
    if (pageIndex === chunks.length - 1) {
      y -= 8; out.push(`0.8 G 28 ${y} m 580 ${y} l S`); y -= 20;
      text(30, 10, `Tickets: ${data.totalTickets}    Value: ${money(data.totalValue)}    Cancelled: ${data.cancelled}`, true); y -= 17;
      text(30, 9, `Chats received: ${data.chatsReceived}    Handled: ${data.chatsHandled}    Missed: ${data.chatsMissed}`); y -= 17;
      text(30, 9, `Unreached clients: ${data.unreached}    Vouchers issued: ${data.vouchers}`); y -= 26;
      text(30, 10, "HANDOVER NOTES", true);
      for (const line of (data.handover || "None").match(/.{1,92}(?:\s|$)/g)?.slice(0, 6) ?? ["None"]) { y -= 14; text(30, 9, line.trim()); }
    }
    out.push("0.45 0.48 0.55 rg", "BT /F 8 Tf 30 24 Td (Generated by Orbit PMS) Tj ET");
    const stream = out.join("\n"), content = add(`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`), page = add(""); pages.push(page); pageBodies.push({ content, page });
  }
  const pagesId = add("");
  pageBodies.forEach(({ content, page }) => objects[page - 1] = `<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F ${font} 0 R /B ${bold} 0 R >> >> /Contents ${content} 0 R >>`);
  objects[pagesId - 1] = `<< /Type /Pages /Kids [${pages.map((page) => `${page} 0 R`).join(" ")}] /Count ${pages.length} >>`;
  const catalog = add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);
  let pdf = "%PDF-1.4\n", offsets = [0];
  objects.forEach((object, index) => { offsets.push(Buffer.byteLength(pdf)); pdf += `${index + 1} 0 obj\n${object}\nendobj\n`; });
  const xref = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => String(offset).padStart(10, "0") + " 00000 n ").join("\n")}\ntrailer << /Size ${objects.length + 1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf);
}
