/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShiftRequestTokenRouteImport } from './routes/shift-request.$token'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiDataRouteImport } from './routes/api.data'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiShiftRequestTokenRouteImport } from './routes/api.shift-request.$token'
import { Route as ApiNotificationsProcessRouteImport } from './routes/api.notifications.process'
import { Route as ApiMailgunWebhookRouteImport } from './routes/api.mailgun.webhook'
import { Route as ApiMailProcessRouteImport } from './routes/api.mail.process'
import { Route as ApiInvitationTokenRouteImport } from './routes/api.invitation.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated/app.tasks'
import { Route as AuthenticatedAppShiftsRouteImport } from './routes/_authenticated/app.shifts'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppTeamsIndexRouteImport } from './routes/_authenticated/app.teams.index'
import { Route as AuthenticatedAppProjectsIndexRouteImport } from './routes/_authenticated/app.projects.index'
import { Route as AuthenticatedAppProjectsKeyRouteImport } from './routes/_authenticated/app.projects.$key'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftRequestTokenRoute = ShiftRequestTokenRouteImport.update({
  id: '/shift-request/$token',
  path: '/shift-request/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiShiftRequestTokenRoute = ApiShiftRequestTokenRouteImport.update({
  id: '/api/shift-request/$token',
  path: '/api/shift-request/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsProcessRoute = ApiNotificationsProcessRouteImport.update({
  id: '/api/notifications/process',
  path: '/api/notifications/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailgunWebhookRoute = ApiMailgunWebhookRouteImport.update({
  id: '/api/mailgun/webhook',
  path: '/api/mailgun/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailProcessRoute = ApiMailProcessRouteImport.update({
  id: '/api/mail/process',
  path: '/api/mail/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationTokenRoute = ApiInvitationTokenRouteImport.update({
  id: '/api/invitation/$token',
  path: '/api/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppShiftsRoute = AuthenticatedAppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTeamsIndexRoute =
  AuthenticatedAppTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectsIndexRoute =
  AuthenticatedAppProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectsKeyRoute =
  AuthenticatedAppProjectsKeyRouteImport.update({
    id: '/projects/$key',
    path: '/projects/$key',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/api/data': typeof ApiDataRoute
  '/api/health': typeof ApiHealthRoute
  '/shift-request/$token': typeof ShiftRequestTokenRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/shifts': typeof AuthenticatedAppShiftsRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invitation/$token': typeof ApiInvitationTokenRoute
  '/api/mail/process': typeof ApiMailProcessRoute
  '/api/mailgun/webhook': typeof ApiMailgunWebhookRoute
  '/api/notifications/process': typeof ApiNotificationsProcessRoute
  '/api/shift-request/$token': typeof ApiShiftRequestTokenRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/projects/$key': typeof AuthenticatedAppProjectsKeyRoute
  '/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/app/teams/': typeof AuthenticatedAppTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/api/data': typeof ApiDataRoute
  '/api/health': typeof ApiHealthRoute
  '/shift-request/$token': typeof ShiftRequestTokenRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/shifts': typeof AuthenticatedAppShiftsRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invitation/$token': typeof ApiInvitationTokenRoute
  '/api/mail/process': typeof ApiMailProcessRoute
  '/api/mailgun/webhook': typeof ApiMailgunWebhookRoute
  '/api/notifications/process': typeof ApiNotificationsProcessRoute
  '/api/shift-request/$token': typeof ApiShiftRequestTokenRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/projects/$key': typeof AuthenticatedAppProjectsKeyRoute
  '/app/projects': typeof AuthenticatedAppProjectsIndexRoute
  '/app/teams': typeof AuthenticatedAppTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/api/data': typeof ApiDataRoute
  '/api/health': typeof ApiHealthRoute
  '/shift-request/$token': typeof ShiftRequestTokenRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/shifts': typeof AuthenticatedAppShiftsRoute
  '/_authenticated/app/tasks': typeof AuthenticatedAppTasksRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invitation/$token': typeof ApiInvitationTokenRoute
  '/api/mail/process': typeof ApiMailProcessRoute
  '/api/mailgun/webhook': typeof ApiMailgunWebhookRoute
  '/api/notifications/process': typeof ApiNotificationsProcessRoute
  '/api/shift-request/$token': typeof ApiShiftRequestTokenRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/projects/$key': typeof AuthenticatedAppProjectsKeyRoute
  '/_authenticated/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/_authenticated/app/teams/': typeof AuthenticatedAppTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/app'
    | '/onboarding'
    | '/accept-invite/$token'
    | '/api/data'
    | '/api/health'
    | '/shift-request/$token'
    | '/app/notifications'
    | '/app/settings'
    | '/app/shifts'
    | '/app/tasks'
    | '/app/team'
    | '/api/auth/$'
    | '/api/invitation/$token'
    | '/api/mail/process'
    | '/api/mailgun/webhook'
    | '/api/notifications/process'
    | '/api/shift-request/$token'
    | '/app/'
    | '/app/projects/$key'
    | '/app/projects/'
    | '/app/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/onboarding'
    | '/accept-invite/$token'
    | '/api/data'
    | '/api/health'
    | '/shift-request/$token'
    | '/app/notifications'
    | '/app/settings'
    | '/app/shifts'
    | '/app/tasks'
    | '/app/team'
    | '/api/auth/$'
    | '/api/invitation/$token'
    | '/api/mail/process'
    | '/api/mailgun/webhook'
    | '/api/notifications/process'
    | '/api/shift-request/$token'
    | '/app'
    | '/app/projects/$key'
    | '/app/projects'
    | '/app/teams'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/accept-invite/$token'
    | '/api/data'
    | '/api/health'
    | '/shift-request/$token'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/shifts'
    | '/_authenticated/app/tasks'
    | '/_authenticated/app/team'
    | '/api/auth/$'
    | '/api/invitation/$token'
    | '/api/mail/process'
    | '/api/mailgun/webhook'
    | '/api/notifications/process'
    | '/api/shift-request/$token'
    | '/_authenticated/app/'
    | '/_authenticated/app/projects/$key'
    | '/_authenticated/app/projects/'
    | '/_authenticated/app/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ShiftRequestTokenRoute: typeof ShiftRequestTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInvitationTokenRoute: typeof ApiInvitationTokenRoute
  ApiMailProcessRoute: typeof ApiMailProcessRoute
  ApiMailgunWebhookRoute: typeof ApiMailgunWebhookRoute
  ApiNotificationsProcessRoute: typeof ApiNotificationsProcessRoute
  ApiShiftRequestTokenRoute: typeof ApiShiftRequestTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shift-request/$token': {
      id: '/shift-request/$token'
      path: '/shift-request/$token'
      fullPath: '/shift-request/$token'
      preLoaderRoute: typeof ShiftRequestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/shift-request/$token': {
      id: '/api/shift-request/$token'
      path: '/api/shift-request/$token'
      fullPath: '/api/shift-request/$token'
      preLoaderRoute: typeof ApiShiftRequestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/process': {
      id: '/api/notifications/process'
      path: '/api/notifications/process'
      fullPath: '/api/notifications/process'
      preLoaderRoute: typeof ApiNotificationsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mailgun/webhook': {
      id: '/api/mailgun/webhook'
      path: '/api/mailgun/webhook'
      fullPath: '/api/mailgun/webhook'
      preLoaderRoute: typeof ApiMailgunWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/process': {
      id: '/api/mail/process'
      path: '/api/mail/process'
      fullPath: '/api/mail/process'
      preLoaderRoute: typeof ApiMailProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitation/$token': {
      id: '/api/invitation/$token'
      path: '/api/invitation/$token'
      fullPath: '/api/invitation/$token'
      preLoaderRoute: typeof ApiInvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tasks': {
      id: '/_authenticated/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/shifts': {
      id: '/_authenticated/app/shifts'
      path: '/shifts'
      fullPath: '/app/shifts'
      preLoaderRoute: typeof AuthenticatedAppShiftsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/teams/': {
      id: '/_authenticated/app/teams/'
      path: '/teams'
      fullPath: '/app/teams/'
      preLoaderRoute: typeof AuthenticatedAppTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects/': {
      id: '/_authenticated/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AuthenticatedAppProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects/$key': {
      id: '/_authenticated/app/projects/$key'
      path: '/projects/$key'
      fullPath: '/app/projects/$key'
      preLoaderRoute: typeof AuthenticatedAppProjectsKeyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppShiftsRoute: typeof AuthenticatedAppShiftsRoute
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppProjectsKeyRoute: typeof AuthenticatedAppProjectsKeyRoute
  AuthenticatedAppProjectsIndexRoute: typeof AuthenticatedAppProjectsIndexRoute
  AuthenticatedAppTeamsIndexRoute: typeof AuthenticatedAppTeamsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppShiftsRoute: AuthenticatedAppShiftsRoute,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppProjectsKeyRoute: AuthenticatedAppProjectsKeyRoute,
  AuthenticatedAppProjectsIndexRoute: AuthenticatedAppProjectsIndexRoute,
  AuthenticatedAppTeamsIndexRoute: AuthenticatedAppTeamsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  ApiDataRoute: ApiDataRoute,
  ApiHealthRoute: ApiHealthRoute,
  ShiftRequestTokenRoute: ShiftRequestTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInvitationTokenRoute: ApiInvitationTokenRoute,
  ApiMailProcessRoute: ApiMailProcessRoute,
  ApiMailgunWebhookRoute: ApiMailgunWebhookRoute,
  ApiNotificationsProcessRoute: ApiNotificationsProcessRoute,
  ApiShiftRequestTokenRoute: ApiShiftRequestTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
